### ISSUE TITLE
ActiveResource::Redirection error with Ruby 1.9.2, Rails 3.0.3

### ISSUE THREAD

**Issue by manuelmeurer** [hybridgroup/taskmapper#10]
I get the following error:

```
ruby-1.9.2-p0 > require 'ticketmaster'
ruby-1.9.2-p0 > require 'ticketmaster-basecamp'
ruby-1.9.2-p0 > basecamp = TicketMaster.new(:basecamp, :domain => 'my_app.basecamphq.com', :token => '...')
ruby-1.9.2-p0 > basecamp.projects
ActiveResource::Redirection: Failed.  Response code = 301.  Response message = Moved Permanently. => https://my_app.basecamphq.com/projects.xml
    from /Users/me/.rvm/gems/ruby-1.9.2-p0@rails3/gems/activeresource-3.0.3/lib/active_resource/connection.rb:125:in `handle_response'
    from /Users/me/.rvm/gems/ruby-1.9.2-p0@rails3/gems/activeresource-3.0.3/lib/active_resource/connection.rb:114:in `request'
    from /Users/me/.rvm/gems/ruby-1.9.2-p0@rails3/gems/activeresource-3.0.3/lib/active_resource/connection.rb:79:in `block in get'
    from /Users/me/.rvm/gems/ruby-1.9.2-p0@rails3/gems/activeresource-3.0.3/lib/active_resource/connection.rb:217:in `with_auth'
    from /Users/me/.rvm/gems/ruby-1.9.2-p0@rails3/gems/activeresource-3.0.3/lib/active_resource/connection.rb:79:in `get'
    from /Users/me/.rvm/gems/ruby-1.9.2-p0@rails3/gems/activeresource-3.0.3/lib/active_resource/base.rb:857:in `find_every'
    from /Users/me/.rvm/gems/ruby-1.9.2-p0@rails3/gems/activeresource-3.0.3/lib/active_resource/base.rb:777:in `find'
    from /Users/me/.rvm/gems/ruby-1.9.2-p0@rails3/gems/ticketmaster-0.5.2/lib/ticketmaster/project.rb:109:in `search'
    from /Users/me/.rvm/gems/ruby-1.9.2-p0@rails3/gems/ticketmaster-0.5.2/lib/ticketmaster/project.rb:100:in `find_by_attributes'
    from /Users/me/.rvm/gems/ruby-1.9.2-p0@rails3/gems/ticketmaster-0.5.2/lib/ticketmaster/project.rb:59:in `find'
    from /Users/me/.rvm/gems/ruby-1.9.2-p0@rails3/gems/ticketmaster-0.5.2/lib/ticketmaster/helper.rb:10:in `easy_finder'
    from /Users/me/.rvm/gems/ruby-1.9.2-p0@rails3/gems/ticketmaster-0.5.2/lib/ticketmaster/provider.rb:44:in `projects'
    from (irb):7
    from /Users/me/.rvm/rubies/ruby-1.9.2-p0/bin/irb:17:in `<main>'
```

Using ticketmaster 0.5.2 and ticketmaster-basecamp 0.1.4

**Comment by kiafaldorius** [comment]
I'm really sorry for the late reply. Things have been busy and your message must have gotten lost in the shuffle.

Your basecamp seems to be set to use ssl. Can you please try passing in :ssl => true as part of the options:

```
basecamp = TicketMaster.new(:basecamp, :domain => 'my_app.basecamphq.com', :token => '...', :ssl => true)
basecamp.projects
```

Also, TicketMaster doesn't officially support 1.9.2 yet (we'll try to eventually, we just don't have the time to consolidate the slight issues with the other providers just yet). In the meantime, we will try to fix the small issues as they come.

Thanks!

**Comment by manuelmeurer** [comment]
Worked beautifully, thanks!
