### ISSUE TITLE
Unfuddle Provider doesn't seem to be implemented

### ISSUE THREAD

**Issue by insignia** [hybridgroup/taskmapper#2]
Hi,

The documentation says that we should take a look at ticketmaster-unfuddle as an example of an implementation of a provider, but it doesn't seem to implement a provider interfase at all.

```
ckozus@ofelia ~/dev/rails[ruby-1.8.7-p174]$ irb
ruby-1.8.7-p174 > require 'rubygems'
 => true 
ruby-1.8.7-p174 > require 'ticketmaster'
 => true 
ruby-1.8.7-p174 > require 'ticketmaster-unfuddle'
 => [] 
ruby-1.8.7-p174 > unfuddle = TicketMaster.new(:unfuddle, {:username => "ckozus", :password => "*******", :subdomain => "insignia4u"})
NameError: uninitialized constant TicketMaster::Provider::Unfuddle
    from /home/ckozus/.rvm/gems/ruby-1.8.7-p174/gems/activesupport-2.3.8/lib/active_support/dependencies.rb:440:in `load_missing_constant'
    from /home/ckozus/.rvm/gems/ruby-1.8.7-p174/gems/activesupport-2.3.8/lib/active_support/dependencies.rb:80:in `const_missing'
    from /home/ckozus/.rvm/gems/ruby-1.8.7-p174/gems/ticketmaster-0.3.10/lib/ticketmaster.rb:42:in `const_get'
    from /home/ckozus/.rvm/gems/ruby-1.8.7-p174/gems/ticketmaster-0.3.10/lib/ticketmaster.rb:42:in `initialize'
    from (irb):4:in `new'
    from (irb):4
    from :0
```

I'm trying to use ticketmaster to access my unfuddle account.

**Comment by deadprogram** [comment]
We need to make a few revisions to this provider to get in sync with the latest gem

**Comment by deadprogram** [comment]
The guy on our team who did this provider will be back from vacation next week... we will get it fixed up then!

**Comment by deadprogram** [comment]
Oops, forgot to close this once the ticketmaster-unfuddle provider was put live a few months back.
